server:
  port: 8081

spring:
  application:
    name: ExpenseTrackerApp
  datasource:
    url: jdbc:oracle:thin:@localhost:1522:xe
    username: deepakdb
    password: deepakdb
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect